#!/bin/sh
export JAVA_HOME=/usr/lib/sdk/openjdk11/jvm/openjdk-11
WORKSPACE_DIR=${WORKSPACE:-${XDG_DATA_HOME:-$HOME/.local/share}/jdtls}
CONFIG_DIR=${JDTLS_CONFIG:-${XDG_CONFIG_HOME:-$HOME/.config}/jdtls}
JDT_DIR=/usr/lib/sdk/jdtls/share

if [ ! -f "$CONFIG_DIR"/config.ini ]; then
    mkdir -p "$CONFIG_DIR"
    ln -s /usr/lib/sdk/jdtls/share/config_linux/config.ini "$CONFIG_DIR"/config.ini
fi

if [ ! -d "$WORKSPACE_DIR" ]; then
    mkdir -p "$WORKSPACE_DIR"
fi

cd ${JDT_DIR}
LAUNCHER=`ls ${JDT_DIR}/plugins/org.eclipse.equinox.launcher_*`
java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.level=ALL -noverify -Xmx1G -jar ${LAUNCHER} -configuration $CONFIG_DIR -data ${WORKSPACE_DIR}
